set(CMAKE_INCLUDE_CURRENT_DIR ON)
find_package(Qt5 COMPONENTS Core Gui Widgets)
include_directories(${CMAKE_CURRENT_BINARY_DIR})

function(BuildBasicExample arg)
    add_executable(${arg} level_basic/${arg}.cpp)
    target_link_libraries(${arg} Qt5::Core Qt5::Gui Qt5::Widgets)
endfunction()

BuildBasicExample(example01)
BuildBasicExample(example02)
BuildBasicExample(example03)
BuildBasicExample(example04)
BuildBasicExample(example05)
BuildBasicExample(example06)
BuildBasicExample(example07)
BuildBasicExample(example08)
BuildBasicExample(example09)
BuildBasicExample(example10)
BuildBasicExample(example11)
BuildBasicExample(example12)
BuildBasicExample(example13)
BuildBasicExample(example14)
BuildBasicExample(example15)
BuildBasicExample(example16)
BuildBasicExample(example17)
BuildBasicExample(example18)
BuildBasicExample(example19)
BuildBasicExample(example20)
BuildBasicExample(example21)
BuildBasicExample(example22)
BuildBasicExample(example23)
BuildBasicExample(example24)
BuildBasicExample(example25)
BuildBasicExample(example26)
BuildBasicExample(example27)
BuildBasicExample(example28)
BuildBasicExample(example29)
BuildBasicExample(example30)
BuildBasicExample(example31)
BuildBasicExample(example32)
BuildBasicExample(example33)
BuildBasicExample(example34)
BuildBasicExample(example35)
BuildBasicExample(example36)
BuildBasicExample(example37)
BuildBasicExample(example38)
BuildBasicExample(example39)
BuildBasicExample(example40)
BuildBasicExample(example41)
BuildBasicExample(example42)
BuildBasicExample(example43)
BuildBasicExample(example44)
BuildBasicExample(example45)
BuildBasicExample(example46)
BuildBasicExample(example47)
BuildBasicExample(example48)
BuildBasicExample(example49)