set(CMAKE_AUTOMOC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
find_package(Qt5 COMPONENTS Core Gui Widgets)
include_directories(${CMAKE_CURRENT_BINARY_DIR})

function(BuildMiddleExample arg)
    file(GLOB HDR level_middle/${arg}/*.h)
    file(GLOB SRC level_middle/${arg}/*.cpp)
    add_executable(${arg} ${HDR} ${SRC})
    target_link_libraries(${arg} Qt5::Core Qt5::Gui Qt5::Widgets)
endfunction()

BuildMiddleExample(example50)
BuildMiddleExample(example51)
BuildMiddleExample(example52)
BuildMiddleExample(example53)
BuildMiddleExample(example54)
BuildMiddleExample(example55)
BuildMiddleExample(example56)
BuildMiddleExample(example57)
BuildMiddleExample(example58)
BuildMiddleExample(example59)
BuildMiddleExample(example60)
BuildMiddleExample(example61)
BuildMiddleExample(example62)
BuildMiddleExample(example63)
BuildMiddleExample(example64)
BuildMiddleExample(example65)
BuildMiddleExample(example66)
BuildMiddleExample(example67)
BuildMiddleExample(example68)
BuildMiddleExample(example69)
BuildMiddleExample(example70)
BuildMiddleExample(example71)
BuildMiddleExample(example72)
BuildMiddleExample(example73)
BuildMiddleExample(example74)
BuildMiddleExample(example75)
BuildMiddleExample(example76)
BuildMiddleExample(example77)
BuildMiddleExample(example78)
BuildMiddleExample(example79)
BuildMiddleExample(example80)
BuildMiddleExample(example81)
BuildMiddleExample(example82)
BuildMiddleExample(example83)
BuildMiddleExample(example84)
BuildMiddleExample(example85)
BuildMiddleExample(example86)
BuildMiddleExample(example87)
BuildMiddleExample(example88)
BuildMiddleExample(example89)
BuildMiddleExample(example90)
BuildMiddleExample(example91)